INSERT INTO `module_2` (`oid`,`moduleid`,`modulename`) VALUES (0,'sv1','Admin');
INSERT INTO `module_2` (`oid`,`moduleid`,`modulename`) VALUES (1,'sv4','User');
INSERT INTO `module_2` (`oid`,`moduleid`,`modulename`) VALUES (2,'area14','EventosAll');
INSERT INTO `module_2` (`oid`,`moduleid`,`modulename`) VALUES (3,'area15','EventosDefault');

INSERT INTO `group_2` (`oid`,`groupname`,`module_2_oid`) VALUES (0,'Admin',0);
INSERT INTO `group_2` (`oid`,`groupname`,`module_2_oid`) VALUES (1,'User',1);
INSERT INTO `group_2` (`oid`,`groupname`,`module_2_oid`) VALUES (2,'UserPremium',2);

INSERT INTO `group_module_2` (`group_2_oid`,`module_2_oid`) VALUES (1,1);
INSERT INTO `group_module_2` (`group_2_oid`,`module_2_oid`) VALUES (1,3);
INSERT INTO `group_module_2` (`group_2_oid`,`module_2_oid`) VALUES (2,1);
INSERT INTO `group_module_2` (`group_2_oid`,`module_2_oid`) VALUES (2,2);

INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (0,'admin0','admin0','admin0@mail.com',NULL,'Admin 0',0);
INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (1,'admin1','admin1','admin1@mail.com',NULL,'Admin 1',0);
INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (2,'josesilva','josesilva','josesilva@mail.com',33.18,'José Silva',1);
INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (3,'antoniomendes','antoniomendes','am@gmail.com',22.59,'António Mendes',2);
INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (4,'miguelantunes','miguelantunes','mjra92@gmail.com',25.87,'Miguel Antunes',1);
INSERT INTO `user_2` (`oid`,`username`,`password`,`email`,`coins`,`name`,`group_2_oid`) VALUES (5,'carolinaferreira','carolinaferreira','cf1998@gmail.com',39.27,'Carolina Ferreira',1);

INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (0,'FC Porto','https://www.thesportsdb.com/images/media/team/badge/small/vtwwwx1471876518.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (1,'SL Benfica','https://www.thesportsdb.com/images/media/team/badge/small/7t684j1520879174.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (2,'Sporting CP','https://www.thesportsdb.com/images/media/team/badge/small/svxpsx1471876338.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (3,'SC Braga','https://www.thesportsdb.com/images/media/team/badge/small/vpxupr1471876624.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (4,'Vitória SC','https://www.thesportsdb.com/images/media/team/badge/small/uvrsxw1471877599.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (5,'Liverpool FC','https://www.thesportsdb.com/images/media/team/badge/uvxuqq1448813372.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (6,'Eintracht Frankfurt','https://www.thesportsdb.com/images/media/team/badge/rurwpy1473453269.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (7,'FC Famalicão','https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Fcf1931.svg/300px-Fcf1931.svg.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (8,'Académica Coimbra','https://www.zerozero.pt/img/logos/equipas/19_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (9,'Moreirense FC','http://www.zerozero.pt/img/logos/equipas/6_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (10,'Belenenses SAD','http://www.zerozero.pt/img/logos/equipas/229965_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (11,'CD Santa Clara','http://www.zerozero.pt/img/logos/equipas/32_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (12,'Rio Ave FC','http://www.zerozero.pt/img/logos/equipas/31_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (13,'CS Marítimo','http://www.zerozero.pt/img/logos/equipas/12_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (14,'Portimonense SC','http://www.zerozero.pt/img/logos/equipas/33_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (15,'Boavista FC','http://www.zerozero.pt/img/logos/equipas/5_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (16,'Vitória FC','http://www.zerozero.pt/img/logos/equipas/35_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (17,'CD Aves','http://www.zerozero.pt/img/logos/equipas/7_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (18,'CD Tondela','http://www.zerozero.pt/img/logos/equipas/4336_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (19,'CD Nacional','http://www.zerozero.pt/img/logos/equipas/27_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (20,'GD Chaves','http://www.zerozero.pt/img/logos/equipas/20_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (21,'CD Feirense','http://www.zerozero.pt/img/logos/equipas/1728_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (22,'FC Paços de Ferreira','http://www.zerozero.pt/img/logos/equipas/13_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (23,'SL Benfica B','http://www.zerozero.pt/img/logos/equipas/4_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (24,'GD Estoril Praia','http://www.zerozero.pt/img/logos/equipas/1734_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (25,'FC Porto B','https://www.thesportsdb.com/images/media/team/badge/small/vtwwwx1471876518.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (26,'FC Penafiel','http://www.zerozero.pt/img/logos/equipas/30_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (27,'SC Covilhã','http://www.zerozero.pt/img/logos/equipas/23_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (28,'Leixões SC','http://www.zerozero.pt/img/logos/equipas/1727_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (29,'CD Cova da Piedade','http://www.zerozero.pt/img/logos/equipas/6505_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (30,'CD Mafra','http://www.zerozero.pt/img/logos/equipas/3696_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (31,'SC Farense','http://www.zerozero.pt/img/logos/equipas/10_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (32,'FC Arouca','http://www.zerozero.pt/img/logos/equipas/3555_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (33,'UD Oliveirense','http://www.zerozero.pt/img/logos/equipas/2199_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (34,'Académico de Viseu','http://www.zerozero.pt/img/logos/equipas/2181_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (35,'Varzim SC','http://www.zerozero.pt/img/logos/equipas/36_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (36,'SC Braga B','https://www.thesportsdb.com/images/media/team/badge/small/vpxupr1471876624.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (37,'Vitória SC B','https://www.thesportsdb.com/images/media/team/badge/small/uvrsxw1471877599.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (38,'Juventus','http://www.zerozero.pt/img/logos/equipas/64_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (39,'Ajax','http://www.zerozero.pt/img/logos/equipas/143_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (40,'FC Barcelona','http://www.zerozero.pt/img/logos/equipas/40_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (41,'Manchester United','http://www.zerozero.pt/img/logos/equipas/87_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (42,'Manchester City','http://www.zerozero.pt/img/logos/equipas/86_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (43,'Tottenham','http://www.zerozero.pt/img/logos/equipas/92_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (44,'Chelsea','http://www.zerozero.pt/img/logos/equipas/81_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (45,'Arsenal','http://www.zerozero.pt/img/logos/equipas/75_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (46,'Leicester City','http://www.zerozero.pt/img/logos/equipas/1136_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (47,'Wolverhampton Wanderers','http://www.zerozero.pt/img/logos/equipas/1135_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (48,'Everton FC','http://www.zerozero.pt/img/logos/equipas/82_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (49,'Watford','http://www.zerozero.pt/img/logos/equipas/2599_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (50,'West Ham','http://www.zerozero.pt/img/logos/equipas/94_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (51,'Bournemouth','http://www.zerozero.pt/img/logos/equipas/4929_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (52,'Crystal Palace','http://www.zerozero.pt/img/logos/equipas/2597_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (53,'Burnley FC','http://www.zerozero.pt/img/logos/equipas/2580_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (54,'Newcastle City','http://www.zerozero.pt/img/logos/equipas/89_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (55,'Southampton','http://www.zerozero.pt/img/logos/equipas/90_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (56,'Brighton & Hove Albion','http://www.zerozero.pt/img/logos/equipas/2601_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (57,'Cardiff City ','http://www.zerozero.pt/img/logos/equipas/2591_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (58,'Fulham FC','http://www.zerozero.pt/img/logos/equipas/83_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (59,'Huddersfield Town','http://www.zerozero.pt/img/logos/equipas/2583_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (60,'Real Madrid','http://www.zerozero.pt/img/logos/equipas/50_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (61,'Real Betis','http://www.zerozero.pt/img/logos/equipas/49_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (62,'Atlético Madrid','http://www.zerozero.pt/img/logos/equipas/39_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (63,'Sevilla FC','http://www.zerozero.pt/img/logos/equipas/53_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (64,'Getafe CF','http://www.zerozero.pt/img/logos/equipas/3753_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (65,'Valencia CF','http://www.zerozero.pt/img/logos/equipas/54_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (66,'Athletic Bilbao','http://www.zerozero.pt/img/logos/equipas/38_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (67,'Alavés','http://www.zerozero.pt/img/logos/equipas/37_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (68,'Real Sociedad','http://www.zerozero.pt/img/logos/equipas/51_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (69,'RCD Espanyol','http://www.zerozero.pt/img/logos/equipas/43_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (70,'CD Leganés','http://www.zerozero.pt/img/logos/equipas/3915_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (71,'SD Eibar','http://www.zerozero.pt/img/logos/equipas/5775_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (72,'Girona FC','http://www.zerozero.pt/img/logos/equipas/5121_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (73,'Villarreal CF','http://www.zerozero.pt/img/logos/equipas/56_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (74,'Levante','http://www.zerozero.pt/img/logos/equipas/2570_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (75,'Celta de Vigo','http://www.zerozero.pt/img/logos/equipas/41_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (76,'Real Valladolid','http://www.zerozero.pt/img/logos/equipas/55_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (77,'Rayo Vallecano','http://www.zerozero.pt/img/logos/equipas/48_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (78,'SD Huesca','http://www.zerozero.pt/img/logos/equipas/5430_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (79,'Paris SG','http://www.zerozero.pt/img/logos/equipas/127_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (80,'Angers','http://www.zerozero.pt/img/logos/equipas/3828_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (81,'AS Monaco','http://www.zerozero.pt/img/logos/equipas/123_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (82,'Amiens','http://www.zerozero.pt/img/logos/equipas/5710_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (83,'Dijon','http://www.zerozero.pt/img/logos/equipas/5146_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (84,'Guingamp','http://www.zerozero.pt/img/logos/equipas/117_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (85,'SM Caen','http://www.zerozero.pt/img/logos/equipas/3841_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (86,'Lille LOSC','http://www.zerozero.pt/img/logos/equipas/120_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (87,'Lyon','http://www.zerozero.pt/img/logos/equipas/121_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (88,'AS Saint-Étinne','http://www.zerozero.pt/img/logos/equipas/3823_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (89,'Marseille','http://www.zerozero.pt/img/logos/equipas/122_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (90,'Montpellier HSC','http://www.zerozero.pt/img/logos/equipas/124_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (91,'Stade de Reims','http://www.zerozero.pt/img/logos/equipas/3825_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (92,'OGC Nice','http://www.zerozero.pt/img/logos/equipas/126_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (93,'RC Strasbourg','http://www.zerozero.pt/img/logos/equipas/131_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (94,'Nimes','http://www.zerozero.pt/img/logos/equipas/3824_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (95,'Rennes','http://www.zerozero.pt/img/logos/equipas/128_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (96,'Bordeaux','http://www.zerozero.pt/img/logos/equipas/116_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (97,'Toulouse FC','http://www.zerozero.pt/img/logos/equipas/1140_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (98,'FC Nantes','http://www.zerozero.pt/img/logos/equipas/125_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (99,'AC Fiorentina','http://www.zerozero.pt/img/logos/equipas/3726_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (100,'Napoli','http://www.zerozero.pt/img/logos/equipas/3735_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (101,'Inter','http://www.zerozero.pt/img/logos/equipas/63_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (102,'AC Milan','http://www.zerozero.pt/img/logos/equipas/66_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (103,'AS Roma','http://www.zerozero.pt/img/logos/equipas/72_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (104,'Atalanta','http://www.zerozero.pt/img/logos/equipas/57_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (105,'Torino FC','http://www.zerozero.pt/img/logos/equipas/73_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (106,'SS Lazio','http://www.zerozero.pt/img/logos/equipas/65_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (107,'Sampdoria','http://www.zerozero.pt/img/logos/equipas/1130_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (108,'US Sassuolo','http://www.zerozero.pt/img/logos/equipas/7908_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (109,'Cagliari','http://www.zerozero.pt/img/logos/equipas/3720_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (110,'SPAL','http://www.zerozero.pt/img/logos/equipas/3746_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (111,'Parma','http://www.zerozero.pt/img/logos/equipas/68_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (112,'Genoa','http://www.zerozero.pt/img/logos/equipas/3728_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (113,'Udinese Calcio','http://www.zerozero.pt/img/logos/equipas/74_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (114,'Bologna FC','http://www.zerozero.pt/img/logos/equipas/58_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (115,'Empoli FC','http://www.zerozero.pt/img/logos/equipas/62_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (116,'Frosinone Calcio','http://www.zerozero.pt/img/logos/equipas/6117_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (117,'Chievo Verona','http://www.zerozero.pt/img/logos/equipas/60_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (118,'Bayern Munique','http://www.zerozero.pt/img/logos/equipas/108_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (119,'Borussia Dortmund','http://www.zerozero.pt/img/logos/equipas/107_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (120,'RB Leipzig','http://www.zerozero.pt/img/logos/equipas/32150_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (121,'Borussia Mönchengladbach','http://www.zerozero.pt/img/logos/equipas/110_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (122,'TSG Hoffenheim','http://www.zerozero.pt/img/logos/equipas/7241_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (123,'Werder Bremen','http://www.zerozero.pt/img/logos/equipas/99_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (124,'Bayer Leverkusen','http://www.zerozero.pt/img/logos/equipas/109_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (125,'Wolfsburg','http://www.zerozero.pt/img/logos/equipas/95_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (126,'Fortuna Düsseldorf','http://www.zerozero.pt/img/logos/equipas/4041_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (127,'Hertha Berlim','http://www.zerozero.pt/img/logos/equipas/101_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (128,'FSV Mainz','http://www.zerozero.pt/img/logos/equipas/4163_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (129,'SC Freiburg','http://www.zerozero.pt/img/logos/equipas/1123_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (130,'FC Augsburg','http://www.zerozero.pt/img/logos/equipas/8210_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (131,'Schalke 04','http://www.zerozero.pt/img/logos/equipas/105_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (132,'VfB Stuttgart','http://www.zerozero.pt/img/logos/equipas/97_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (133,'FC Nürnberg','http://www.zerozero.pt/img/logos/equipas/112_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (134,'Hannover 96','http://www.zerozero.pt/img/logos/equipas/103_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (135,'Slavia Praha','http://www.zerozero.pt/img/logos/equipas/151_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (136,'PSV Eindhoven','http://www.zerozero.pt/img/logos/equipas/147_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (137,'Feyenoord','http://www.zerozero.pt/img/logos/equipas/1121_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (138,'Basaksehir','http://www.zerozero.pt/img/logos/equipas/8702_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (139,'Galatasaray','http://www.zerozero.pt/img/logos/equipas/134_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (140,'Besiktas','http://www.zerozero.pt/img/logos/equipas/144_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (141,'Trabzonspor','http://www.zerozero.pt/img/logos/equipas/1109_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (142,'Fenerbahçe','http://www.zerozero.pt/img/logos/equipas/2145_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (143,'KRC Genk','http://www.zerozero.pt/img/logos/equipas/1776_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (144,'Club Brugge','http://www.zerozero.pt/img/logos/equipas/145_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (145,'Standard de Liège','http://www.zerozero.pt/img/logos/equipas/1775_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (146,'RSC Anderlecht','http://www.zerozero.pt/img/logos/equipas/140_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (147,'PAOK','http://www.zerozero.pt/img/logos/equipas/1116_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (148,'Olympiacos','http://www.zerozero.pt/img/logos/equipas/136_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (149,'AEK Athens','http://www.zerozero.pt/img/logos/equipas/148_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (150,'Panathinaikos','http://www.zerozero.pt/img/logos/equipas/137_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (151,'Atromitos FC','http://www.zerozero.pt/img/logos/equipas/1918_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (152,'Lokomotiv Moskva','http://www.zerozero.pt/img/logos/equipas/142_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (153,'Crvena Zvezda','http://www.zerozero.pt/img/logos/equipas/1097_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (154,'Shakhtar Donetsk','http://www.zerozero.pt/img/logos/equipas/160_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (155,'CSKA Moskva','http://www.zerozero.pt/img/logos/equipas/171_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (156,'Viktoria Plzen','http://www.zerozero.pt/img/logos/equipas/2068_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (157,'BSC Young Boys','http://www.zerozero.pt/img/logos/equipas/1102_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (158,'Dinamo Zagreb','http://www.zerozero.pt/img/logos/equipas/149_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (159,'Zenit','http://www.zerozero.pt/img/logos/equipas/2090_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (160,'RB Salzburg','http://www.zerozero.pt/img/logos/equipas/1119_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (161,'FK Krasnodar','http://www.zerozero.pt/img/logos/equipas/25480_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (162,'Dynamo Kyiv','http://www.zerozero.pt/img/logos/equipas/141_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (163,'Celtic FC','http://www.zerozero.pt/img/logos/equipas/139_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (164,'BATE Borisov','http://www.zerozero.pt/img/logos/equipas/180_imgbank.png');
INSERT INTO `team` (`oid`,`name`,`simbolo_2`) VALUES (165,'Spartak Moskva','https://www.zerozero.pt/img/logos/equipas/1115_imgbank.png');

INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (0,'Liga NOS','Portugal');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (1,'Ledman LigaPro','Portugal');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (2,'Taça de Portugal','Portugal');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (3,'Taça da Liga','Portugal');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (4,'La Liga','Espanha');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (5,'Premier League','Inglaterra');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (6,'Ligue 1','França');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (7,'Serie A','Itália');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (8,'Bundesliga','Alemanha');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (9,'UEFA Champions League','Europa');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (10,'UEFA Europa League','Europa');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (11,'UEFA SuperCup','Europa');
INSERT INTO `competition` (`oid`,`name`,`country`) VALUES (12,'UEFA Euro 2020 Qualifiers','Europa');

INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,0);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,1);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,2);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,3);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,4);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,9);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,10);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,11);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,12);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,13);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,14);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,15);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,16);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,17);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,18);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,19);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,20);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (0,21);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,7);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,8);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,22);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,23);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,24);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,25);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,26);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,27);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,28);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,29);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,30);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,31);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,32);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,33);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,34);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,35);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,36);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (1,37);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (2,0);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (2,2);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,40);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,60);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,61);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,62);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,63);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,64);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,65);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,66);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,67);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,68);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,69);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,70);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,71);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,72);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,73);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,74);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,75);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,76);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,77);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (4,78);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,5);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,41);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,42);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,43);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,44);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,45);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,46);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,47);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,48);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,49);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,50);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,51);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,52);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,53);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,54);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,55);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,56);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,57);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,58);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (5,59);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,79);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,80);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,81);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,82);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,83);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,84);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,85);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,86);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,87);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,88);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,89);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,90);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,91);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,92);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,93);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,94);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,95);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,96);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,97);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (6,98);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,38);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,99);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,100);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,101);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,102);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,103);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,104);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,105);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,106);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,107);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,108);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,109);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,110);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,111);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,112);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,113);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,114);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,115);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,116);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (7,117);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,6);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,118);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,119);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,120);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,121);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,122);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,123);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,124);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,125);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,126);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,127);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,128);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,129);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,130);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,131);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,132);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,133);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (8,134);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,0);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,5);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,38);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,39);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,40);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,41);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,42);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (9,43);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,1);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,6);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,44);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,45);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,65);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,73);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,100);
INSERT INTO `competition_team` (`competition_oid`,`team_oid`) VALUES (10,135);

INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (2,0,2.15,3,3.3,'1',' ',18,0,15);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (3,0,2.25,3.1,3.15,'1',' ',16,0,14);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (4,0,5,3.9,1.6,'1',' ',19,0,2);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (5,0,1.75,3.3,4.75,'1',' ',4,0,17);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (6,0,2.2,3.1,3.25,'1',' ',10,0,12);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (7,0,1.9,3.25,4,'1',' ',9,0,20);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (8,0,7.5,4.25,1.4,'1',' ',21,0,3);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (9,0,1.13,7,17,'1',' ',0,0,11);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (10,0,1.12,7.25,17,'1',' ',1,0,13);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (11,0,1.27,5.25,9,'1',' ',42,5,43);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (12,0,1.62,4,4.5,'1',' ',51,5,58);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (13,0,2.7,3.25,2.4,'1',' ',47,5,45);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (14,1,5.12,4.4,1.98,'1',' ',41,5,42);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (15,1,1.7,3.8,4.25,'1',' ',40,9,5);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (16,1,2.2,3.25,3.1,'1',' ',43,9,39);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (18,1,1.75,3.75,4.5,'1',' ',6,10,1);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (19,1,1.62,4,4.5,'1',' ',100,10,45);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (20,1,1.32,4.75,8.3,'1',' ',44,10,135);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (21,1,1.7,3.7,4.7,'1',' ',65,10,73);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (22,1,1.5,4.5,7.55,'1',' ',38,7,99);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (23,1,3,3.55,2.5,'1',' ',121,8,120);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (24,1,1.69,3.99,5.48,'0','1-2',38,9,39);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (25,1,1.49,5.68,9.25,'0','3-0',40,9,41);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (26,1,3.68,3.72,2.47,'0','1-4',0,9,5);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (27,1,1.31,6.16,11.27,'0','4-3',42,9,43);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (28,0,1.9,3.21,4.34,'0','2-2',20,0,10);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (29,0,2.27,3.03,3.13,'0','1-1',11,0,9);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (30,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (31,0,8.92,4.71,1.35,'0','0-3',14,0,0);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (32,0,4.21,3.61,1.83,'0','1-3',17,0,2);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (33,0,3.22,3.32,2.26,'0','2-1',12,0,4);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (34,0,1.37,4.53,9.05,'0','3-0',3,0,18);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (35,0,1.16,7.52,13.03,'0','4-2',1,0,16);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (36,0,4.77,4.02,1.71,'0','1-1',70,4,60);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (37,0,1.72,3.91,5.26,'0','2-0',5,5,44);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (38,0,2.29,3.09,3.39,'0','2-0',7,1,8);
INSERT INTO `event` (`oid`,`type`,`oddv`,`odde`,`oddd`,`status`,`result`,`team_oid`,`competition_oid`,`team_oid_2`) VALUES (39,0,4.37,3.23,1.92,'0','1-1',25,1,22);

INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,1,NULL,3,NULL,NULL);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,2,NULL,2,NULL,NULL);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,4,3,NULL,2,NULL,NULL);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,4,4,3,3.9,3.9);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,5,14,3,1.98,1.98);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,6,10,3,2.24,1.12);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,2,7,26,3,4.94,2.47);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,9,27,3,2.62,1.31);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,10,24,3,0,1.69);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,11,18,3,7.5,3.75);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,12,21,3,3.7,3.7);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,13,39,3,3.23,3.23);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,1,14,38,3,2.29,2.29);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,15,36,3,0,1.71);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,1,16,35,3,1.16,1.16);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,18,31,3,1.35,1.35);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,19,32,3,0,3.61);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,20,33,3,0,2.26);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,21,39,2,0,1.92);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,22,38,2,0,3.09);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,23,37,2,3.44,1.72);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,24,36,2,0,1.71);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,1,25,35,2,1.16,1.16);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,26,34,2,0,4.53);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,27,32,2,1.83,1.83);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,5,28,31,2,6.75,1.35);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,29,9,2,2.26,1.13);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,30,4,2,3.9,3.9);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,31,10,2,7.25,7.25);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,32,11,2,10.5,5.25);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,2,33,29,4,0,3.13);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,34,4,4,1.6,1.6);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,35,3,4,3.1,3.1);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,2,36,31,4,2.7,1.35);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,37,37,4,0,3.91);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,38,33,4,6.44,3.22);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,39,28,4,3.21,3.21);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,40,12,4,4,4);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,41,35,4,2.32,1.16);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,1,42,39,5,0,4.37);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,43,38,5,4.58,2.29);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,5,44,37,5,8.6,1.72);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,2,45,36,5,0,1.71);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,46,34,5,2.74,1.37);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,47,32,5,0,3.61);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (3,1,48,31,5,1.35,1.35);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,3,49,13,5,9.75,3.25);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,2,50,9,5,2.26,1.13);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,1,51,7,5,1.9,1.9);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (1,5,52,10,5,5.6000000000000005,1.12);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,2,53,4,5,7.8,3.9);
INSERT INTO `bet` (`result`,`amount`,`oid`,`event_oid`,`user_2_oid`,`profit`,`odd`) VALUES (2,1,54,2,5,3,3);

INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (7,'Parabens! Ganhou uma aposta!',7,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (9,'Parabens! Ganhou uma aposta!',9,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (10,'Perdeu uma aposta.',10,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (13,'Parabens! Ganhou uma aposta!',13,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (14,'Parabens! Ganhou uma aposta!',14,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (15,'Perdeu uma aposta.',15,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (16,'Parabens! Ganhou uma aposta!',16,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (18,'Parabens! Ganhou uma aposta!',18,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (19,'Perdeu uma aposta.',19,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (20,'Perdeu uma aposta.',20,3);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (21,'Perdeu uma aposta.',21,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (22,'Perdeu uma aposta.',22,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (23,'Parabens! Ganhou uma aposta!',23,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (24,'Perdeu uma aposta.',24,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (25,'Parabens! Ganhou uma aposta!',25,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (26,'Perdeu uma aposta.',26,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (27,'Parabens! Ganhou uma aposta!',27,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (28,'Parabens! Ganhou uma aposta!',28,2);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (33,'Perdeu uma aposta.',33,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (36,'Parabens! Ganhou uma aposta!',36,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (37,'Perdeu uma aposta.',37,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (38,'Parabens! Ganhou uma aposta!',38,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (39,'Parabens! Ganhou uma aposta!',39,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (41,'Parabens! Ganhou uma aposta!',41,4);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (42,'Perdeu uma aposta.',42,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (43,'Parabens! Ganhou uma aposta!',43,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (44,'Parabens! Ganhou uma aposta!',44,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (45,'Perdeu uma aposta.',45,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (46,'Parabens! Ganhou uma aposta!',46,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (47,'Perdeu uma aposta.',47,5);
INSERT INTO `notification` (`oid`,`message`,`bet_oid`,`user_2_oid`) VALUES (48,'Parabens! Ganhou uma aposta!',48,5);
