# Generated by Django 2.2 on 2019-06-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190609_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamCompetition',
        ),
    ]
